# Site settings
name: Bhor Sharma
title: Bhor Sharma | Software developer
description: Software developer | Competitive Programmer | Freelancer
url: ""
baseurl: ""
email: bhorsharma560@gmail.com
cover: https://harsh9200.github.io/img/og.png
logo: https://harsh9200.github.io/img/emojis/technologist.png
resume: https://harsh9200.github.io/resume.pdf
social:
  - title: email
    url: mailto:bhorsharma98@gmail.com
  - title: github
    url: https://github.com/Bhorshrm
  - title: linkedin
    url: https://www.linkedin.com/in/bhorshrm/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
